=head1 NAME

Workaholicd - A simple daemon to watch databases and notify events by invoking Web APIs

=head1 DESCRIPTION

TBD.

=head1 DISTRIBUTION

Latest version of the workaholicd script is available at:
<https://github.com/wakaba/workaholicd>.

=head1 AUTHOR

Wakaba (id:wakabatan) <wakabatan@hatena.ne.jp>.

=head1 LICENSE

Copyright 2012 Hatena <http://www.hatena.ne.jp/>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
